from selenium.webdriver.common.by import By
from src.test.common.page import Page
import time

class StockAdjustmentAddPage(Page):
    adjustmentType_input = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[1]/div/form/div/div[1]/div/div/div/div/div/input')
    adjustmentType_xlk = (By.XPATH,'/html/body/div[5]/ul[2]/li')
    warehouse_input = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[1]/div/form/div/div[4]/div/div/div/div/div/div/input')
    warehouse_xlk = (By.XPATH,'/html/body/div[6]/ul[2]/li/span')
    businessDepartment_input = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[1]/div/form/div/div[6]/div/div/div/div/div/div/input')
    businessDepartment_xlk = (By.XPATH,'/html/body/div[7]/ul[2]/li/span')
    businessUser_input = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[1]/div/form/div/div[7]/div/div/div/div/div/div/input')
    businessUser_xlk = (By.XPATH,'/html/body/div[8]/ul[2]/li/span')
    detailsadd_button = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[2]/div[2]/div/div[1]/div/div[1]/button')
    addWarehouse_button = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[2]/div[2]/div/div[1]/div/div[2]/ul/li[2]')
    shangping1 = (By.XPATH,'/html/body/div[20]/div[2]/div/div/div[2]/div/div[3]/div/div[1]/div[4]/div[2]/table/tbody/tr[1]/td[1]/div/label/span/input')
    shangping2 = (By.XPATH,'/html/body/div[20]/div[2]/div/div/div[2]/div/div[3]/div/div[1]/div[4]/div[2]/table/tbody/tr[2]/td[1]/div/label/span/input')
    quding_button = (By.XPATH,'/html/body/div[20]/div[2]/div/div/div[3]/div/div/button[2]/span')
    tijiao_button = (By.XPATH,'/html/body/div[1]/main/article/div/div[2]/div[1]/div[3]/button[2]/span')

    def stockAdjustment_LocationNumber(self,LocationNumber,warehouse,businessDepartment,businessUser):
        time.sleep(1)
        self.find_element(*self.adjustmentType_input).click()
        time.sleep(1)
        self.find_element(*self.adjustmentType_input).send_keys(LocationNumber)
        time.sleep(1)
        self.find_element(*self.adjustmentType_xlk).click()
        time.sleep(1)
        self.find_element(*self.warehouse_input).click()
        time.sleep(1)
        self.find_element(*self.warehouse_input).send_keys(warehouse)
        time.sleep(1)
        self.find_element(*self.warehouse_xlk).click()
        time.sleep(1)
        self.find_element(*self.businessDepartment_input).click()
        time.sleep(1)
        self.find_element(*self.businessDepartment_input).send_keys(businessDepartment)
        time.sleep(1)
        self.find_element(*self.businessDepartment_xlk).click()
        time.sleep(1)
        self.find_element(*self.businessUser_input).click()
        time.sleep(1)
        self.find_element(*self.businessUser_input).clear()
        self.find_element(*self.businessUser_input).send_keys(businessUser)
        time.sleep(1)
        self.find_element(*self.businessUser_xlk).click()
        time.sleep(1)
        self.find_element(*self.detailsadd_button).click()
        time.sleep(1)
        self.find_element(*self.addWarehouse_button).click()
        time.sleep(1)
        self.find_element(*self.shangping1).click()
        self.find_element(*self.shangping2).click()
        time.sleep(1)
        queding_js = 'document.querySelector("body > div:nth-child(23) > div.ivu-modal-wrap > div > div > div.ivu-modal-footer > div > div > button.ivu-btn.ivu-btn-primary > span").scrollIntoView()'
        self.driver.execute_script(queding_js)
        self.find_element(*self.quding_button).click()
        time.sleep(1)
        self.find_element(*self.tijiao_button).click()
        time.sleep(1)